language: node_js

node_js:
  - 13
  - 12
  - 11
  - 9
  - 7
  - 6

branches:
  only:
    - master
    - develop

cache:
  npm: true
  directories:
    - node_modules

install:
  - npm install

script:
  - npm test
